sonar.projectKey=ArchLens-Fiap_archlens-ai-processing
sonar.organization=archlens-fiap
sonar.projectName=archlens-ai-processing
sonar.sources=app/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=tests/**
